language: node_js
dist: trusty
node_js:
- '8'
- '6'
services:
- mysql
- postgresql
before_install:
- sudo pip install futoin-cid
- sudo bash test/db_config.sh
script:
- rm -rf node_modules
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid prepare
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid run test

