language: node_js
dist: trusty
node_js:
- '8'
- '6'

before_install:
- sudo pip install futoin-cid
- bash test/db_config.sh
script:
- nodeVer=$TRAVIS_NODE_VERSION cid prepare
- nodeVer=$TRAVIS_NODE_VERSION cid run test

